namespace: authgear

mainServer:
  image: __replace_me__

  env:
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    ADMIN_API_AUTH: "jwt"
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

adminServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

resolverServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

portalServer:
  image: __replace_me__

  ingress:
    host: __replace_me__.example.com
    tls:
      secretName: __replace_me__

  authgearHost: __replace_me__.example.com

  configMap:
    ingressTemplate:
      name: __replace_me__

  env:
    DATABASE_URL: postgres://localhost
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    SMTP_HOST: __replace_me__
    SMTP_PORT: 587
    SMTP_MODE: normal
    SMTP_USERNAME: __replace_me__
    SMTP_PASSWORD: __replace_me__
    MAIL_SENDER: __replace_me__
    MAIL_REPLY_TO: __replace_me__
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"
    AUTHGEAR_APP_ID: __replace_me__
    AUTHGEAR_CLIENT_ID: __replace_me__
    AUTHGEAR_ENDPOINT: https://__replace_me__.example.com
    ADMIN_API_TYPE: "static"
    ADMIN_API_AUTH: "jwt"
    ADMIN_API_ENDPOINT: __replace_me__.example.com
    ADMIN_API_HOST_TEMPLATE: "{{ .AppID }}.example.com"
    APP_HOST_SUFFIX: ".example.com"
    APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_TYPE: none
    APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_SECRET_NAME: __replace_me__
    APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_KIND: Issuer
    APP_KUBERNETES_DEFAULT_DOMAIN_TLS_CERT_ISSUER_NAME: __replace_me__
    APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_TYPE: none
    APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_SECRET_NAME: __replace_me__
    APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_KIND: Issuer
    APP_KUBERNETES_CUSTOM_DOMAIN_TLS_CERT_ISSUER_NAME: __replace_me__
    MAX_OWNED_APPS: "-1"

appCustomResources:
  path: ""
  volume: {}

portalCustomResources:
  path: ""
  volume: {}
