namespace: authgear

mainServer:
  image: __replace_me__

  ingress:
    host: __replace_me__.example.com
    tls:
      secretName: __replace_me__

  env:
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    ADMIN_API_AUTH: "jwt"
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

adminServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

resolverServer:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 300m
      memory: 64Mi

portalServer:
  image: __replace_me__

  ingress:
    host: __replace_me__.example.com
    tls:
      secretName: __replace_me__

  authgearHost: __replace_me__.example.com

  env:
    TRUST_PROXY: "true"
    LOG_LEVEL: "warn"
    SENTRY_DSN: ""
    CONFIG_SOURCE_TYPE: "kubernetes"
    CONFIG_SOURCE_KUBE_NAMESPACE: "authgear-apps"
    AUTHGEAR_CLIENT_ID: __replace_me__
    AUTHGEAR_ENDPOINT: https://__replace_me__.example.com
    ADMIN_API_TYPE: "static"
    ADMIN_API_AUTH: "jwt"
    ADMIN_API_ENDPOINT: __replace_me__.example.com
    ADMIN_API_HOST_TEMPLATE: "{{ .AppID }}.example.com"
    APP_HOST_TEMPLATE: "{{ .AppID }}.example.com"
    APP_SECRET_DATABASE_URL: postgres://localhost
    APP_SECRET_DATABASE_SCHEMA: public
    APP_SECRET_REDIS_URL: redis://localhost/0
    APP_SECRET_SMTP_HOST: localhost
    APP_SECRET_SMTP_PORT: "587"
    APP_SECRET_SMTP_MODE: normal
    APP_SECRET_SMTP_USERNAME: __replace_me__
    APP_SECRET_SMTP_PASSWORD: __replace_me__
    APP_SECRET_TWILIO_ACCOUNT_SID: __replace_me__
    APP_SECRET_TWILIO_AUTH_TOKEN: __replace_me__
